build:
  image: python:3
  stage: build
  before_script:
    - apt install -y git
    - git submodule update --init --recursive
    - bash update_oscal.sh
    - pip install -r requirements.txt
  script:
    - python parse_meta.py
  artifacts:
    when: always
    paths:
      - oscal-content/
      - pyoscal/

unittest:
  image: python:3
  stage: test 
  dependencies:
    - build
  before_script:
    - pip install -r requirements.txt
  script:
    - python unit_test.py
  artifacts:
    when: always

package:
  stage: deploy
  image: python:3
  variables:
    TWINE_REPOSITORY_URL: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi
    TWINE_USERNAME: gitlab-ci-token
    TWINE_PASSWORD: $CI_JOB_TOKEN
  dependencies:
    - build
  before_script:
    - pip install twine wheel
  script:
    - cd pyoscal
    - sed -i "s/version='0\.9\..*'/version='0\.9\.${CI_JOB_ID}'/g" setup.py #update version
    - python setup.py bdist_wheel
    - python -m twine upload dist/*.whl --verbose
  only: # Only Publish Master on Main Repo (not forks)
    - master@shrgroup/oss/python/pyoscal



    
